[package]
name = "dephy-types"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["derive", "borsh/std", "rc"]
derive = ["borsh/derive"]
rc = ["borsh/rc"]

[dependencies]
borsh = { version = "1.3.0", default-features = false }
